print('==== Exercicio004 ====')
v = input('Digite um N: ')
print('O tipo primitivo desse valor é', type(v))
print('É numerico? ', v.isnumeric())
print('É alpha? ', v.isalpha())
print('Pertence a tabela ascii? ', v.isascii())
print('É um Digito? ', v.isdigit())
print('É um N decimal? ', v.isdecimal())
print('Apenas letras minusculas?', v.islower())
print('É um espaço?', v.isspace())
print('É um identificador? ', v.isidentifier())
print('Pode ser impresso? ', v.isprintable())
print('Apenas letra maiusculas? {}'.format(v.isupper()))

